### ISSUE TITLE
Editing mkdocs.yml

### ISSUE THREAD

**Issue by Stanzilla** [capriosa/mkdocs-cms#40]
Hey there, I tried this and it sort of works but there is no way to actually get new sites out with it, because you still have to add them to `mkdocs.yml` or remove the `nav` config and let mkdocs auto-discover, which is not really a solution for me.

Did you have any plans to let this edit `mkdocs.yml` as well? I'm not exactly sure how this would work and if you even have any long term goals with this project. Thank you :)

**Comment by capriosa** [comment]
I'm not working on this project any longer. Sorry :(

**Comment by Stanzilla** [comment]
Alright :)
